default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fix_tiny_arms_development
  username: bruno
  password:
  host: /var/run/postgresql

test:
  <<: *default
  database: fix_tiny_arms_test
  username: bruno
  password:
  host: /var/run/postgresql

production:
  <<: *default
  database: fix_tiny_arms_production
  username: fix_tiny_arms
  password: <%= ENV["FIX_TINY_ARMS_DATABASE_PASSWORD"] %>
